version: "3.1"
services:
  mysql5:
    build:
      context: mysql5
    container_name: mysql5_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
#    ports:
#      - 3306:3306
  mysql8:
    build:
      context: mysql8
    container_name: mysql8_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
#    ports:
#      - 3306:3306
