version: 2

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_mysql5:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building image
          command: docker-compose build mysql5
      - run:
          name: Saving image
          command: docker save -o ~/mysql5 project_mysql5
      - persist_to_workspace:
          root: ~/
          paths:
            - mysql5
  build_mysql8:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building image
          command: docker-compose build mysql8
      - run:
          name: Saving image
          command: docker save -o ~/mysql8 project_mysql8
      - persist_to_workspace:
          root: ~/
          paths:
            - mysql8
  publish_mysql5:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading image
          command: docker load -i ~/mysql5
      - run:
          name: Logging into dockerhub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Publishing image
          command: |
            docker tag project_mysql5 ${DOCKER_USERNAME}/mysql:5
            docker push ${DOCKER_USERNAME}/mysql:5
      - run:
          name: Clearing docker images
          command: docker image prune -a -f
  publish_mysql8:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading image
          command: docker load -i ~/mysql8
      - run:
          name: Logging into dockerhub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Publishing image
          command: |
            docker tag project_mysql8 ${DOCKER_USERNAME}/mysql:8
            docker tag project_mysql8 ${DOCKER_USERNAME}/mysql:latest
            docker push ${DOCKER_USERNAME}/mysql:8
            docker push ${DOCKER_USERNAME}/mysql:latest
      - run:
          name: Clearing docker images
          command: docker image prune -a -f

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout
      - build_mysql5:
          requires:
            - checkout
      - build_mysql8:
          requires:
            - checkout
      - publish_mysql5:
          requires:
            - build_mysql5
          filters:
            branches:
              only:
                - main
      - publish_mysql8:
          requires:
            - build_mysql8
          filters:
            branches:
              only:
                - main
