version: 2

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_mysql5:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building mysql 5
          command: docker-compose build mysql5
      - run:
          name: Saving images
          command: |
            mkdir ~/images
            docker save -o ~/images/mysql5 project_mysql5
      - persist_to_workspace:
          root: ~/
          paths:
            - images
  build_mysql8:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building mysql 8
          command: docker-compose build mysql8
      - run:
          name: Saving images
          command: |
            mkdir ~/images
            docker save -o ~/images/mysql8 project_mysql8
      - persist_to_workspace:
          root: ~/
          paths:
            - images
  publish:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading images
          command: |
            docker load -i ~/images/mysql5
            docker load -i ~/images/mysql8
      - run:
          command: docker image ls
#       - run:
#           name: Logging into dockerhub
#           command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
#       - run:
#           name: Publishing mysql:5
#           command: |
#             docker tag project_mysql5 ${DOCKER_USERNAME}/mysql:5
#             docker push ${DOCKER_USERNAME}/mysql:5
#       - run:
#           name: Publishing mysql:8
#           command: |
#             docker tag project_mysql8 ${DOCKER_USERNAME}/mysql:8
#             docker tag project_mysql8 ${DOCKER_USERNAME}/mysql:latest
#             docker push ${DOCKER_USERNAME}/mysql:8
#             docker push ${DOCKER_USERNAME}/mysql:latest

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout
      - build_mysql5:
          requires:
            - checkout
      - build_mysql8:
          requires:
            - checkout
      - publish:
          requires:
            - build_mysql5
            - build_mysql8
          filters:
            branches:
              only:
                - main
