name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#     - name: Building mysql5
#       run: |
#         docker-compose build mysql5

#     - name: Building mysql8
#       run: |
#         docker-compose build mysql8
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./mysql8
        push: false
        tags: syednaeem15191/mysql:latest,syednaeem15191/mysql:8

#    - name: Tag images
#      run: |
#        docker tag mysql_mysql8 syednaeem15191/mysql:8
#        docker tag mysql_mysql8 syednaeem15191/mysql:latest
#        docker tag mysql_mysql5 syednaeem15191/mysql:5

    - name: docker image ls
      run: docker image ls

#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
