name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Persist workspace
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: ./
  mysql5:
    name: Building mysql5
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Attach workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build mysql5
      uses: docker/build-push-action@v3
      with:
        context: ./mysql5
        push: true
        tags: syednaeem15191/mysql:5
    - name: Clear docker images
        run: docker image rm syednaeem15191/mysql
  mysql8:
    name: Building mysql8
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Attach workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace
    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build mysql8
      uses: docker/build-push-action@v3
      with:
        context: ./mysql5
        push: false
        tags: syednaeem15191/mysql:8, syednaeem15191/mysql:latest
    - name: Clear docker images
        run: docker image rm syednaeem15191/mysql
