name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: ls -la
      run: ls -la
    - name: pwd
      run: pwd
#     - name: Upload math result for job 1
#       uses: actions/upload-artifact@v3
#       with:
#         name: homework
#         path: math-homework.txt
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Build mysql5
      uses: docker/build-push-action@v3
      with:
        context: ./mysql5
        push: false
        tags: syednaeem15191/mysql:5
    - name: Build mysql8
      uses: docker/build-push-action@v3
      with:
        context: ./mysql8
        push: false
        tags: syednaeem15191/mysql:latest,syednaeem15191/mysql:8
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: docker image ls
      run: docker image ls
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
