name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Building images
      run: docker-compose build

    - name: Tag images
      run: |
        docker tag mysql_mysql8 syednaeem15191/mysql:8
        docker tag mysql_mysql5 syednaeem15191/mysql:5

    - name: docker image ls
      run: docker image ls

#    - name: Login to Docker Hub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
