name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Persist workspace
      uses: actions/upload-artifact@v3
      with:
        name: workspace
        path: ./
  mysql5:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - name: Attach workspace
      uses: actions/download-artifact@v3
      with:
        name: workspace
    - name: Build mysql5
      uses: docker/build-push-action@v3
      with:
        context: ./mysql5
        push: false
        tags: syednaeem15191/mysql:5
#     - name: Build mysql8
#       uses: docker/build-push-action@v3
#       with:
#         context: ./mysql8
#         push: false
#         tags: syednaeem15191/mysql:latest,syednaeem15191/mysql:8
    - name: Save image
      run: |
        mkdir ~/images
        docker save -o ~/images/mysql5 syednaeem15191/mysql:5
    - name: Persist images
      uses: actions/upload-artifact@v3
      with:
        name: images
        path: ~/images
  deploy:
    needs: [mysql5]
    runs-on: ubuntu-latest
    steps:
    - name: Attach images
      uses: actions/download-artifact@v3
      with:
        name: images
        path: ~/images
    - name: ls -la
      run: |
        cd ~/images
        ls -la
#     - name: Load images
#       run: |
#         docker load -i ~/images/mysql5
    - name: docker image ls
      run: docker image ls
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
