name: Build images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build mysql8
      uses: docker/build-push-action@v3
      with:
        context: ./mysql8
        push: false
        tags: syednaeem15191/mysql:latest,syednaeem15191/mysql:8

    - name: Build mysql5
      uses: docker/build-push-action@v3
      with:
        context: ./mysql5
        push: false
        tags: syednaeem15191/mysql:5

    - name: docker image ls
      run: docker image ls
